name: Trigger Web Rebuild
on:
  push:
    branches:
      - main
    paths:
      - 'R*/**'       # Trigger only on rule changes
      - 'README.md'   # Or main readme changes

jobs:
  notify-web:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Trigger FlowLint Web Rebuild
        uses: peter-evans/repository-dispatch@v3 # v3.0.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: Replikanti/flowlint-web
          event-type: examples-updated
